// Mocks generated by Mockito from annotations
// in vankar_samaj_matrimony/test/features/profile/profile_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vankar_samaj_matrimony/core/network/dio_client.dart' as _i2;
import 'package:vankar_samaj_matrimony/features/profile/data/profile_api.dart'
    as _i4;
import 'package:vankar_samaj_matrimony/features/profile/data/profile_models.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDioClient_0 extends _i1.SmartFake implements _i2.DioClient {
  _FakeDioClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMatrimonialProfileModel_1 extends _i1.SmartFake
    implements _i3.MatrimonialProfileModel {
  _FakeMatrimonialProfileModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReferenceDataModel_2 extends _i1.SmartFake
    implements _i3.ReferenceDataModel {
  _FakeReferenceDataModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompletenessModel_3 extends _i1.SmartFake
    implements _i3.CompletenessModel {
  _FakeCompletenessModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileApi extends _i1.Mock implements _i4.ProfileApi {
  MockProfileApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DioClient get dioClient => (super.noSuchMethod(
        Invocation.getter(#dioClient),
        returnValue: _FakeDioClient_0(
          this,
          Invocation.getter(#dioClient),
        ),
      ) as _i2.DioClient);

  @override
  _i5.Future<_i3.MatrimonialProfileModel> getMyProfile() => (super.noSuchMethod(
        Invocation.method(
          #getMyProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.MatrimonialProfileModel>.value(
            _FakeMatrimonialProfileModel_1(
          this,
          Invocation.method(
            #getMyProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i3.MatrimonialProfileModel>);

  @override
  _i5.Future<_i3.MatrimonialProfileModel> createProfile(
          _i3.CreateProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [request],
        ),
        returnValue: _i5.Future<_i3.MatrimonialProfileModel>.value(
            _FakeMatrimonialProfileModel_1(
          this,
          Invocation.method(
            #createProfile,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.MatrimonialProfileModel>);

  @override
  _i5.Future<_i3.MatrimonialProfileModel> updateProfile(
          _i3.UpdateProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [request],
        ),
        returnValue: _i5.Future<_i3.MatrimonialProfileModel>.value(
            _FakeMatrimonialProfileModel_1(
          this,
          Invocation.method(
            #updateProfile,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.MatrimonialProfileModel>);

  @override
  _i5.Future<void> deleteProfile() => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ReferenceDataModel> getReferenceData() => (super.noSuchMethod(
        Invocation.method(
          #getReferenceData,
          [],
        ),
        returnValue:
            _i5.Future<_i3.ReferenceDataModel>.value(_FakeReferenceDataModel_2(
          this,
          Invocation.method(
            #getReferenceData,
            [],
          ),
        )),
      ) as _i5.Future<_i3.ReferenceDataModel>);

  @override
  _i5.Future<_i3.CompletenessModel> getCompleteness() => (super.noSuchMethod(
        Invocation.method(
          #getCompleteness,
          [],
        ),
        returnValue:
            _i5.Future<_i3.CompletenessModel>.value(_FakeCompletenessModel_3(
          this,
          Invocation.method(
            #getCompleteness,
            [],
          ),
        )),
      ) as _i5.Future<_i3.CompletenessModel>);
}
