class GovDepartments {
  static const List<String> gujaratGov = [
    'Select Category',
    'Gujarat Administrative Service',
    'Gujarat Police',
    'Education / Teachers',
    'Health / Doctors / Nurses',
    'Revenue / Mamlatdar',
    'Agriculture',
    'Forest',
    'Engineering / R&B',
    'Water Resources',
    'Panchayat',
    'Municipality / Urban Development',
    'Labour',
    'Social Welfare',
    'Tribal Development',
    'Transport',
    'Government Colleges',
    'Government Hospitals',
    'GSEB / Education Boards',
    'Gujarat Government Corporations / Boards / PSUs',
  ];

  static const List<String> centralGov = [
    'Select Category',
    'IAS / Central Civil Services',
    'IPS',
    'Indian Revenue Service',
    'Indian Railway Services',
    'Postal Department',
    'Income Tax',
    'Customs & GST',
    'Central Excise',
    'Defence / Army',
    'Navy',
    'Air Force',
    'DRDO',
    'ISRO',
    'Atomic Energy',
    'Central Universities',
    'IIT / NIT',
    'AIIMS',
    'Central Government Hospitals',
    'Central Government Schools / KVS',
    'CBI',
    'CAG',
    'Election Commission',
    'UPSC',
    'Central PSUs',
    'Others',
  ];
}
