import { Injectable } from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";

@Injectable()
export class MasterDataService {
  constructor(private readonly prisma: PrismaService) {}

  async getAllMasterData() {
    const states = await this.prisma.state.findMany({
      where: { isActive: true },
      include: {
        districts: {
          where: { isActive: true },
          include: {
            talukas: {
              where: { isActive: true },
              select: { id: true, name: true, gujaratiName: true },
            },
          },
        },
      },
    });

    // Formatting for frontend AppData compatibility
    const gujaratDistricts: Record<string, string[]> = {
      "Select District": ["Select Taluka"],
    };

    const gujaratState = states.find((s) => s.name.toLowerCase() === "gujarat");
    if (gujaratState) {
      for (const district of gujaratState.districts) {
        gujaratDistricts[district.name] = district.talukas.map((t) => t.name);
      }
    }

    // Static data that is not yet in DB
    const educationDegrees = [
      "Select Degree",
      "No Formal Education",
      "Primary School",
      "5th Fail",
      "5th Pass",
      "8th Fail",
      "8th Pass",
      "10th Fail",
      "10th Pass / SSC",
      "12th Fail",
      "12th Pass / HSC",
      "12th Arts",
      "12th Commerce",
      "12th Science",
      "12th Vocational",
      "ITI",
      "Certificate Course",
      "Diploma",
      "B.A.",
      "B.Com.",
      "B.Sc.",
      "B.B.A.",
      "B.C.A.",
      "B.E.",
      "B.Tech.",
      "M.A.",
      "M.Com.",
      "M.Sc.",
      "M.B.A.",
      "M.C.A.",
      "M.E.",
      "M.Tech.",
      "Ph.D.",
      "Other Qualification (અન્ય)",
    ];

    const abroadCountries = [
      "Select Country (દેશ પસંદ કરો)",
      "Afghanistan — અફઘાનિસ્તાન",
      "Albania — અલ્બેનિયા",
      "Algeria — અલ્જીરિયા",
      "Andorra — એન્ડોરા",
      "Angola — અંગોલા",
      "Antigua and Barbuda — એન્ટિગુઆ અને બાર્બુડા",
      "Argentina — આર્જેન્ટિના",
      "Armenia — આર્મેનિયા",
      "Australia — ઓસ્ટ્રેલિયા",
      "Austria — ઓસ્ટ્રિયા",
      "Azerbaijan — અઝરબૈજાન",
      "Bahamas — બહામાસ",
      "Bahrain — બહેરીન",
      "Bangladesh — બાંગ્લાદેશ",
      "Barbados — બાર્બાડોસ",
      "Belarus — બેલારુસ",
      "Belgium — બેલ્જિયમ",
      "Belize — બેલીઝ",
      "Benin — બેનિન",
      "Bhutan — ભૂટાન",
      "Bolivia — બોલિવિયા",
      "Bosnia and Herzegovina — બોસ્નિયા અને હર્ઝેગોવિના",
      "Botswana — બોત્સ્વાના",
      "Brazil — બ્રાઝિલ",
      "Brunei — બ્રુનેઈ",
      "Bulgaria — બલ્ગેરિયા",
      "Burkina Faso — બુર્કિના ફાસો",
      "Burundi — બુરુન્ડી",
      "Cabo Verde — કાબો વર્ડે",
      "Cambodia — કંબોડિયા",
      "Cameroon — કેમરૂન",
      "Canada — કેનેડા",
      "Central African Republic — મધ્ય આફ્રિકન પ્રજાસત્તાક",
      "Chad — ચાડ",
      "Chile — ચિલી",
      "China — ચીન",
      "Colombia — કોલંબિયા",
      "Comoros — કોમોરોસ",
      "Congo — કોંગો",
      "Costa Rica — કોસ્ટા રિકા",
      "Côte d'Ivoire — કોટ દિ'વોઆર",
      "Croatia — ક્રોએશિયા",
      "Cuba — ક્યુબા",
      "Cyprus — સાયપ્રસ",
      "Czechia — ચેકિયા",
      "Democratic Republic of the Congo — ડેમોક્રેટિક રિપબ્લિક ઓફ કોંગો",
      "Denmark — ડેનમાર્ક",
      "Djibouti — જિબુટી",
      "Dominica — ડોમિનિકા",
      "Dominican Republic — ડોમિનિકન રિપબ્લિક",
      "Ecuador — એક્વાડોર",
      "Egypt — ઇજિપ્ત",
      "El Salvador — અલ સાલ્વાડોર",
      "Equatorial Guinea — ઇક્વેટોરિયલ ગિની",
      "Eritrea — એરિટ્રિયા",
      "Estonia — એસ્ટોનિયા",
      "Eswatini — એસ્વાતિની",
      "Ethiopia — ઇથોપિયા",
      "Fiji — ફિજી",
      "Finland — ફિનલેન્ડ",
      "France — ફ્રાન્સ",
      "Gabon — ગેબોન",
      "Gambia — ગેમ્બિયા",
      "Georgia — જ્યોર્જિયા",
      "Germany — જર્મની",
      "Ghana — ઘાના",
      "Greece — ગ્રીસ",
      "Grenada — ગ્રેનેડા",
      "Guatemala — ગ્વાટેમાલા",
      "Guinea — ગિની",
      "Guinea-Bissau — ગિની-બિસાઉ",
      "Guyana — ગયાના",
      "Haiti — હૈતી",
      "Honduras — હોન્ડુરાસ",
      "Hungary — હંગેરી",
      "Iceland — આઇસલેન્ડ",
      "India — ભારત",
      "Indonesia — ઇન્ડોનેશિયા",
      "Iran — ઈરાન",
      "Iraq — ઈરાક",
      "Ireland — આયર્લેન્ડ",
      "Israel — ઇઝરાયેલ",
      "Italy — ઇટાલી",
      "Jamaica — જમૈકા",
      "Japan — જાપાન",
      "Jordan — જોર્ડન",
      "Kazakhstan — કઝાકિસ્તાન",
      "Kenya — કેન્યા",
      "Kiribati — કિરિબાટી",
      "Kuwait — કુવૈત",
      "Kyrgyzstan — કિર્ગિઝસ્તાન",
      "Laos — લાઓસ",
      "Latvia — લાતવિયા",
      "Lebanon — લેબનોન",
      "Lesotho — લેસોથો",
      "Liberia — લાઇબેરિયા",
      "Libya — લિબિયા",
      "Liechtenstein — લિખ્ટેનસ્ટાઇન",
      "Lithuania — લિથુઆનિયા",
      "Luxembourg — લક્ઝમબર્ગ",
      "Madagascar — મેડાગાસ્કર",
      "Malawi — માલાવી",
      "Malaysia — મલેશિયા",
      "Maldives — માલદીવ",
      "Mali — માલી",
      "Malta — માલ્ટા",
      "Marshall Islands — માર્શલ ટાપુઓ",
      "Mauritania — મોરિટાનિયા",
      "Mauritius — મોરિશિયસ",
      "Mexico — મેક્સિકો",
      "Micronesia — માઇક્રોનેશિયા",
      "Moldova — મોલડોવા",
      "Monaco — મોનાકો",
      "Mongolia — મંગોલિયા",
      "Montenegro — મોન્ટેનેગ્રો",
      "Morocco — મોરોક્કો",
      "Mozambique — મોઝામ્બિક",
      "Myanmar — મ્યાનમાર",
      "Namibia — નામિબિયા",
      "Nauru — નાઉરુ",
      "Nepal — નેપાળ",
      "Netherlands — નેધરલેન્ડ્સ",
      "New Zealand — ન્યૂઝીલેન્ડ",
      "Nicaragua — નિકારાગુઆ",
      "Niger — નાઇજર",
      "Nigeria — નાઇજીરિયા",
      "North Korea — ઉત્તર કોરિયા",
      "North Macedonia — ઉત્તર મેસેડોનિયા",
      "Norway — નોર્વે",
      "Oman — ઓમાન",
      "Pakistan — પાકિસ્તાન",
      "Palau — પલાઉ",
      "Palestine — પેલેસ્ટાઇન",
      "Panama — પનામા",
      "Papua New Guinea — પાપુઆ ન્યૂ ગિની",
      "Paraguay — પેરાગ્વે",
      "Peru — પેરુ",
      "Philippines — ફિલિપાઇન્સ",
      "Poland — પોલેન્ડ",
      "Portugal — પોર્ટુગલ",
      "Qatar — કતાર",
      "Romania — રોમાનિયા",
      "Russia — રશિયા",
      "Rwanda — રવાંડા",
      "Saint Kitts and Nevis — સેન્ટ કિટ્સ અને નેવિસ",
      "Saint Lucia — સેન્ટ લુસિયા",
      "Saint Vincent and the Grenadines — સેન્ટ વિન્સેન્ટ અને ગ્રેનેડાઇન્સ",
      "Samoa — સામોઆ",
      "San Marino — સાન મેરિનો",
      "São Tomé and Príncipe — સાઓ તોમે અને પ્રિન્સિપે",
      "Saudi Arabia — સાઉદી અરેબિયા",
      "Senegal — સેનેગલ",
      "Serbia — સર્બિયા",
      "Seychelles — સેશેલ્સ",
      "Sierra Leone — સિયેરા લિયોન",
      "Singapore — સિંગાપોર",
      "Slovakia — સ્લોવાકિયા",
      "Slovenia — સ્લોવેનિયા",
      "Solomon Islands — સોલોમન ટાપુઓ",
      "Somalia — સોમાલિયા",
      "South Africa — દક્ષિણ આફ્રિકા",
      "South Korea — દક્ષિણ કોરિયા",
      "South Sudan — દક્ષિણ સુદાન",
      "Spain — સ્પેન",
      "Sri Lanka — શ્રીલંકા",
      "Sudan — સુદાન",
      "Suriname — સુરીનામ",
      "Sweden — સ્વીડન",
      "Switzerland — સ્વિટ્ઝર્લેન્ડ",
      "Syria — સીરિયા",
      "Tajikistan — તાજિકિસ્તાન",
      "Tanzania — તાન્ઝાનિયા",
      "Thailand — થાઇલેન્ડ",
      "Timor-Leste — તિમોર-લેસ્તે",
      "Togo — ટોગો",
      "Tonga — ટોંગા",
      "Trinidad and Tobago — ટ્રિનિડાડ અને ટોબેગો",
      "Tunisia — ટ્યુનિશિયા",
      "Türkiye — તુર્કિયે",
      "Turkmenistan — તુર્કમેનિસ્તાન",
      "Tuvalu — તુવાલુ",
      "Uganda — યુગાન્ડા",
      "Ukraine — યુક્રેન",
      "United Arab Emirates — સંયુક્ત આરબ અમીરાત",
      "United Kingdom — યુનાઇટેડ કિંગડમ",
      "United States — યુનાઇટેડ સ્ટેટ્સ",
      "Uruguay — ઉરુગ્વે",
      "Uzbekistan — ઉઝબેકિસ્તાન",
      "Vanuatu — વનુઆતુ",
      "Vatican City — વેટિકન સિટી",
      "Venezuela — વેનેઝુએલા",
      "Vietnam — વિયેતનામ",
      "Yemen — યમન",
      "Zambia — ઝામ્બિયા",
      "Zimbabwe — ઝિમ્બાબ્વે",
      "Other Country (અન્ય દેશ)",
    ];

    const privateSectors = [
      "Select Category",
      "IT / Software Development",
      "Banking / Financial Services (BFSI)",
      "Healthcare / Medical / Hospital",
      "Engineering / Manufacturing",
      "Education / Teaching",
    ];

    const businessSectors = [
      "Select Category",
      "Retail / Shop (કરિયાણા/અન્ય દુકાન)",
      "Wholesale / Trading (જથ્થાબંધ વેપાર)",
      "Manufacturing / Factory (ઉત્પાદન)",
      "Agriculture / Farming (ખેતી)",
      "Real Estate / Construction",
    ];

    const incomeRanges = [
      "Select Income",
      "₹0–1 લાખ",
      "₹1–2 લાખ",
      "₹2–3 લાખ",
      "₹3–5 લાખ",
      "₹5–10 લાખ",
      "₹10–15 લાખ",
      "₹15–20 લાખ",
      "₹20 લાખથી વધુ",
    ];

    const religionOptions = [
      "Select Religion",
      "હિન્દુ ધર્મ (Hinduism)",
      "બૌદ્ધ ધર્મ (Buddhism)",
    ];

    return {
      gujaratDistricts,
      educationDegrees,
      abroadCountries,
      privateSectors,
      businessSectors,
      incomeRanges,
      religionOptions,
    };
  }
}
